import Head from "next/head";
import Image from "next/image";
import PrimaryLayout from "../components/layout/primary-layout";
import { NextPageWithLayout } from "./page";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-slate-50 min-h-screen">
        <div className="container mx-auto px-2 md:px-16 py-10">
          <div className="relative w-full h-96 overflow-hidden rounded-lg ">
            <Image
              src="/images/trip-1.jpg"
              layout="fill"
              objectFit="cover"
              alt="trip tip"
              priority
            />

            <div className="absolute top-0 left-0 h-96 w-full bg-[rgba(0,0,0,0.2)]" />

            <div className="absolute bottom-10 left-8 md:left-10">
              <h1 className="text-4xl md:text-[4rem] font-bold text-white shadow-sm">
                Get inspired for your next trip
              </h1>
              <p className="text-white text-md mt-2 lg:mt-6 font-normal">
                Ideas. Ispiration. And 100% fun!!
              </p>

              <button className="bg-white py-2 px-6 rounded-full text-center shadow-md text-sm font-medium mt-4 hover:bg-slate-100 transition duration-200 hover:shadow-xl active:scale-75">
                See more
              </button>
            </div>
          </div>

          <div className="mt-16">
            <h2 className="text-md font-bold mb-10">
              Explore popular experiences
            </h2>
            <div className="flex flex-col lg:flex-row lg:justify-between">
              <div className="lg:w-1/2 flex space-x-4">
                {[3, 2, 1].map((n, i) => (
                  <div
                    key={i}
                    className="relative w-96 lg:w-52 h-80 overflow-hidden rounded-lg"
                  >
                    <Image
                      src={`/images/trip-${n}.jpg`}
                      layout="fill"
                      objectFit="cover"
                      alt="trip tip"
                    />
                  </div>
                ))}
              </div>
              <div className="lg:w-1/2 px-4 mt-8 lg:mt-0 lg:px-10 flex flex-col justify-center bg-slate-50 rounded-lg">
                <h2 className="font-bold text-2xl lg:w-2/3">
                  From food tours to rainforest villages, these experiences let
                  you deep dive on African culture.
                </h2>
                <button className="bg-black text-white w-fit py-2 px-6 rounded-full text-center shadow-md text-sm font-medium mt-4 hover:bg-slate-800 transition duration-200 hover:shadow-xl active:scale-75">
                  See more
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;

Home.getLayout = (page) => <PrimaryLayout>{page}</PrimaryLayout>;
